In [189]:
import pandas as pd
import numpy as np
df = pd.read_csv('gmGeo.csv')

### RFE: Onto Recursive Feature Elimination

In [190]:
pd.set_option('display.max_columns', 500)

In [191]:
df.describe(include='all')

Unnamed: 0    playDispNm    next_gmDays     pre_gmDays  \
count   154014.000000        154014  154014.000000  154014.000000   
unique            NaN           895            NaN            NaN   
top               NaN  Corey Brewer            NaN            NaN   
freq              NaN           482            NaN            NaN   
mean     77006.500000           NaN       2.349851       2.390562   
std      44460.156517           NaN       1.277117       1.296341   
min          0.000000           NaN       0.000000       0.000000   
25%      38503.250000           NaN       2.000000       2.000000   
50%      77006.500000           NaN       2.000000       2.000000   
75%     115509.750000           NaN       3.000000       3.000000   
max     154013.000000           NaN       9.000000       9.000000   

               gmTime teamAbbr     teamDayOff        playMin     playHeight  \
count   154014.000000   154014  154014.000000  154014.000000  154014.000000   
unique            NaN       30            NaN            NaN            NaN   
top               NaN       SA            NaN            NaN            NaN   
freq              NaN     5770            NaN            NaN            NaN   
mean        15.682535      NaN       2.076396      22.988676      79.011609   
std          5.880749      NaN       1.049777      10.690116       3.431578   
min          1.000000      NaN       0.000000       0.000000      69.000000   
25%          9.000000      NaN       2.000000      15.000000      77.000000   
50%         19.000000      NaN       2.000000      24.000000      79.000000   
75%         20.000000      NaN       2.000000      31.000000      82.000000   
max         22.000000      NaN      11.000000      60.000000      87.000000   

           playWeight        playPTS        playAST         playTO  \
count   154014.000000  154014.000000  154014.000000  154014.000000   
unique            NaN            NaN            NaN            NaN   
top               NaN            NaN            NaN            NaN   
freq              NaN            NaN            NaN            NaN   
mean       217.932941       9.855974       2.185892       1.297285   
std         25.942307       7.932366       2.532465       1.382802   
min        149.000000       0.000000       0.000000       0.000000   
25%        200.000000       4.000000       0.000000       0.000000   
50%        220.000000       8.000000       1.000000       1.000000   
75%        237.000000      15.000000       3.000000       2.000000   
max        290.000000      62.000000      25.000000      12.000000   

              playSTL        playBLK         playPF        playFGA  \
count   154014.000000  154014.000000  154014.000000  154014.000000   
unique            NaN            NaN            NaN            NaN   
top               NaN            NaN            NaN            NaN   
freq              NaN            NaN            NaN            NaN   
mean         0.737595       0.483047       1.880232       7.989767   
std          0.983238       0.883062       1.441477       5.502435   
min          0.000000       0.000000       0.000000       0.000000   
25%          0.000000       0.000000       1.000000       4.000000   
50%          0.000000       0.000000       2.000000       7.000000   
75%          1.000000       1.000000       3.000000      11.000000   
max          8.000000      11.000000       6.000000      44.000000   

              playFGM        playFG%        play2PA        play2PM  \
count   154014.000000  154014.000000  154014.000000  154014.000000   
unique            NaN            NaN            NaN            NaN   
top               NaN            NaN            NaN            NaN   
freq              NaN            NaN            NaN            NaN   
mean         3.676510       0.425244       5.714013       2.853195   
std          2.982805       0.247963       4.556545       2.624615   
min          0.000000       0.000000       0.000000       0.0

In [192]:
dataset = df.drop(columns=['Unnamed: 0','playDispNm','teamAbbr','Team','Arena','opptAbbr','Geo_loc','pre_Geo'])

In [193]:
dataset.fillna(0,inplace=True)

In [194]:
dataset.columns

Index(['next_gmDays', 'pre_gmDays', 'gmTime', 'teamDayOff', 'playMin',
       'playHeight', 'playWeight', 'playPTS', 'playAST', 'playTO', 'playSTL',
       'playBLK', 'playPF', 'playFGA', 'playFGM', 'playFG%', 'play2PA',
       'play2PM', 'play2P%', 'play3PA', 'play3PM', 'play3P%', 'playFTA',
       'playFTM', 'playFT%', 'playORB', 'playDRB', 'playTRB', 'opptDayOff',
       'gmYear', 'gmMonth', 'gmWeek', 'gmDay', 'gmDayofweek', 'gmDayofyear',
       'gmIs_month_end', 'gmIs_month_start', 'gmIs_quarter_end',
       'gmIs_quarter_start', 'gmIs_year_end', 'gmIs_year_start', 'gmElapsed',
       'playBYear', 'playBMonth', 'playBWeek', 'playBDay', 'playBDayofweek',
       'playBDayofyear', 'playBIs_month_end', 'playBIs_month_start',
       'playBIs_quarter_end', 'playBIs_quarter_start', 'playBIs_year_end',
       'playBIs_year_start', 'playBElapsed', 'IsStarter', 'teamConfIsEast',
       'opptConfIsEast', 'teamRsltIsWin', 'opptRsltltIsWin', 'teamLocIsHome',
       'opptLocIsHome', 'playPos_C'

In [195]:
#get rid of playmin
feature_name = ['next_gmDays', 'pre_gmDays', 'gmTime', 'teamDayOff',
       'playHeight', 'playWeight', 'playPTS', 'playAST', 'playTO', 'playSTL',
       'playBLK', 'playPF', 'playFGA', 'playFGM', 'playFG%', 'play2PA',
       'play2PM', 'play2P%', 'play3PA', 'play3PM', 'play3P%', 'playFTA',
       'playFTM', 'playFT%', 'playORB', 'playDRB', 'playTRB', 'opptDayOff',
       'gmYear', 'gmMonth', 'gmWeek', 'gmDay', 'gmDayofweek', 'gmDayofyear',
       'gmIs_month_end', 'gmIs_month_start', 'gmIs_quarter_end',
       'gmIs_quarter_start', 'gmIs_year_end', 'gmIs_year_start', 'gmElapsed',
       'playBYear', 'playBMonth', 'playBWeek', 'playBDay', 'playBDayofweek',
       'playBDayofyear', 'playBIs_month_end', 'playBIs_month_start',
       'playBIs_quarter_end', 'playBIs_quarter_start', 'playBIs_year_end',
       'playBIs_year_start', 'playBElapsed', 'IsStarter', 'teamConfIsEast',
       'opptConfIsEast', 'teamRsltIsWin', 'opptRsltltIsWin', 'teamLocIsHome',
       'opptLocIsHome', 'playPos_C', 'playPos_F', 'playPos_G', 'playPos_PF',
       'playPos_PG', 'playPos_SF', 'playPos_SG', 'teamDiv_Atlantic',
       'teamDiv_Central', 'teamDiv_Northwest', 'teamDiv_Pacific',
       'teamDiv_Southeast', 'teamDiv_Southwest', 'opptDiv_Atlantic',
       'opptDiv_Central', 'opptDiv_Northwest', 'opptDiv_Pacific',
       'opptDiv_Southeast', 'opptDiv_Southwest', 'age', 'Seats', 'Year_Open','pre_gm_miles']

In [196]:
feature_name

['next_gmDays',
 'pre_gmDays',
 'gmTime',
 'teamDayOff',
 'playHeight',
 'playWeight',
 'playPTS',
 'playAST',
 'playTO',
 'playSTL',
 'playBLK',
 'playPF',
 'playFGA',
 'playFGM',
 'playFG%',
 'play2PA',
 'play2PM',
 'play2P%',
 'play3PA',
 'play3PM',
 'play3P%',
 'playFTA',
 'playFTM',
 'playFT%',
 'playORB',
 'playDRB',
 'playTRB',
 'opptDayOff',
 'gmYear',
 'gmMonth',
 'gmWeek',
 'gmDay',
 'gmDayofweek',
 'gmDayofyear',
 'gmIs_month_end',
 'gmIs_month_start',
 'gmIs_quarter_end',
 'gmIs_quarter_start',
 'gmIs_year_end',
 'gmIs_year_start',
 'gmElapsed',
 'playBYear',
 'playBMonth',
 'playBWeek',
 'playBDay',
 'playBDayofweek',
 'playBDayofyear',
 'playBIs_month_end',
 'playBIs_month_start',
 'playBIs_quarter_end',
 'playBIs_quarter_start',
 'playBIs_year_end',
 'playBIs_year_start',
 'playBElapsed',
 'IsStarter',
 'teamConfIsEast',
 'opptConfIsEast',
 'teamRsltIsWin',
 'opptRsltltIsWin',
 'teamLocIsHome',
 'opptLocIsHome',
 'playPos_C',
 'playPos_F',
 'playPos_G',
 'playPos_PF',
 '

In [197]:
num_features = len(feature_name)

In [198]:
from sklearn.model_selection import train_test_split
X = dataset[feature_name]
y = dataset['playMin']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=46)

In [199]:
%%time
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE

estimator = LinearRegression(n_jobs = -1)
rfe = RFE(estimator, num_features, step = 1)

CPU times: user 22 µs, sys: 1 µs, total: 23 µs
Wall time: 24.8 µs


In [200]:
dataset[feature_name].shape

(154014, 84)

In [201]:
selected_data = rfe.fit_transform(dataset[feature_name], dataset['playMin'])

In [202]:
type(selected_data)

numpy.ndarray

In [203]:
rfe.support_

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [204]:
np.array(feature_name)[rfe.support_]

array(['next_gmDays', 'pre_gmDays', 'gmTime', 'teamDayOff', 'playHeight',
       'playWeight', 'playPTS', 'playAST', 'playTO', 'playSTL', 'playBLK',
       'playPF', 'playFGA', 'playFGM', 'playFG%', 'play2PA', 'play2PM',
       'play2P%', 'play3PA', 'play3PM', 'play3P%', 'playFTA', 'playFTM',
       'playFT%', 'playORB', 'playDRB', 'playTRB', 'opptDayOff', 'gmYear',
       'gmMonth', 'gmWeek', 'gmDay', 'gmDayofweek', 'gmDayofyear',
       'gmIs_month_end', 'gmIs_month_start', 'gmIs_quarter_end',
       'gmIs_quarter_start', 'gmIs_year_end', 'gmIs_year_start',
       'gmElapsed', 'playBYear', 'playBMonth', 'playBWeek', 'playBDay',
       'playBDayofweek', 'playBDayofyear', 'playBIs_month_end',
       'playBIs_month_start', 'playBIs_quarter_end',
       'playBIs_quarter_start', 'playBIs_year_end', 'playBIs_year_start',
       'playBElapsed', 'IsStarter', 'teamConfIsEast', 'opptConfIsEast',
       'teamRsltIsWin', 'opptRsltltIsWin', 'teamLocIsHome',
       'opptLocIsHome', 'playPos_C', 'p

In [205]:
model = LinearRegression()
model.fit(selected_data, dataset['playMin'])
model.score(selected_data, dataset['playMin'])

0.8018748725678759

### RFCV

In [206]:
data = dataset.copy()
X = data[feature_name]
y = data['playMin']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=25)

In [207]:
%%time
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
import numpy as np

selectors = []

for idx in list(range(1, num_features, 1))[::-1]:
    # 1. create an estimator
    estimator = LinearRegression(n_jobs=-1)
    # 2. perform rfe with the idx number of features
    rfe = RFE(estimator, idx, step=1)
    # 3. reduce the dataset to the number of features
    X_train_rfe = rfe.fit_transform(X_train,y_train)
    X_test_rfe = rfe.transform(X_test)
    
    # 4. compute the accuracy score and append to the list
    estimator.fit(X_train_rfe,y_train)
    score = estimator.score(X_test_rfe,y_test)
    selectors.append(np.array([rfe, score, idx]))

CPU times: user 30min 56s, sys: 1min 12s, total: 32min 8s
Wall time: 8min 45s


In [208]:
wrapped_selectors = np.array(selectors)

In [209]:
y_values = wrapped_selectors[:, 1]
x_values = wrapped_selectors[:, -1]

In [210]:
x_values

array([83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67,
       66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50,
       49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1], dtype=object)

In [211]:
from graph import trace_values, plot
trace = trace_values(x_values, y_values)
plot([trace])

### Choosing the correct number

In [212]:
top_selector = selectors[-3]
top_selector

array([RFE(estimator=LinearRegression(copy_X=True, fit_intercept=True, n_jobs=-1,
                               normalize=False),
    n_features_to_select=3, step=1, verbose=0),
       0.5030839288890503, 3], dtype=object)

In [213]:
top_rfe = top_selector[0]
np.array(feature_name)[top_rfe.support_]

array(['playFGM', 'play2PM', 'play3PM'], dtype='<U21')

In [214]:
from sklearn.feature_selection import RFECV

In [215]:
from sklearn.feature_selection import RFECV

estimator = LinearRegression(n_jobs=-1)
rfe = RFECV(estimator, step=1, cv=5)
X_train_rfe = rfe.fit_transform(X_train,y_train)

In [216]:
rfecv_scores = rfe.grid_scores_
rfecv_scores

array([0.46340025, 0.54787669, 0.54941799, 0.60460084, 0.65440932,
       0.65470381, 0.65619369, 0.65776306, 0.66187319, 0.66189908,
       0.6625437 , 0.66567943, 0.71454573, 0.71969662, 0.7266873 ,
       0.72726149, 0.72801181, 0.75210956, 0.75449238, 0.77339058,
       0.77571711, 0.78129611, 0.78138951, 0.78591337, 0.7881697 ,
       0.79207971, 0.7923168 , 0.79288607, 0.79359828, 0.79440067,
       0.79514271, 0.79626752, 0.79645408, 0.79668246, 0.79670084,
       0.79727327, 0.79782312, 0.79785568, 0.79792037, 0.79828213,
       0.79840014, 0.79842184, 0.79864662, 0.79913261, 0.79935251,
       0.79953533, 0.79980845, 0.8000186 , 0.8000358 , 0.80011008,
       0.80011211, 0.80011678, 0.80014703, 0.80030641, 0.80030242,
       0.80033224, 0.80037078, 0.80051234, 0.80055802, 0.80056164,
       0.80069143, 0.80080657, 0.80081242, 0.80081348, 0.80084664,
       0.80084753, 0.8008456 , 0.80103405, 0.80104941, 0.80111258,
       0.8011125 , 0.80116479, 0.80129148, 0.80129486, 0.80130

In [217]:
from graph import plot, trace_values
trace_rfecv = trace_values(num_features, rfecv_scores)
plot([trace])