In [1]:
import numpy as np

In [3]:
temperatures = np.random.randint(0,105,150)

In [4]:
temperatures[0:3]

array([97, 92, 60])

In [14]:
$ y=temperatures*5+40 $

SyntaxError: invalid syntax (<ipython-input-14-6695ce8f9f2b>, line 1)

In [10]:
# y = temperatures*5 + 40 + error_i(irreducible error)

In [11]:
params = np.array([5,40])

In [16]:
ones=np.ones(150)

In [26]:
features_matrix = np.hstack((temperatures.reshape(-1,1), ones.reshape(-1,1)))

In [36]:
errors = np.random.randint(-30,30,150)

In [27]:
features_matrix.shape

(150, 2)

In [28]:
features_matrix[:3,:]

array([[97.,  1.],
       [92.,  1.],
       [60.,  1.]])

In [29]:
params

array([ 5, 40])

In [31]:
customers = features_matrix@params

In [38]:
noisy_customers = customers + errors

In [32]:
from graph import trace_values, plot

In [40]:
from sklearn.linear_model import LinearRegression

In [41]:
model = LinearRegression(fit_intercept = False)

In [42]:
model.fit(features_matrix, customers)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=1, normalize=False)

In [43]:
model.coef_

array([ 5., 40.])

In [45]:
model.predict()

TypeError: predict() missing 1 required positional argument: 'X'

In [ ]:
variance_model = LinearRegression(fit_intercept=False)
variance_model.fit()

In [35]:
trace = trace_values(temperatures,customers)
plot([trace])

In [39]:
trace = trace_values(temperatures,noisy_customers)
plot([trace])

In [6]:
temperatures * 5

array([485, 460, 300,   5, 220,  45,  15, 370, 370,  90, 305, 445, 110,
       130, 490, 495, 265, 380,  75, 460, 245,  30, 340,  60, 470, 330,
       495, 415, 235, 465, 505, 440, 100, 150, 375,  45, 125, 145,  60,
       240, 430, 340, 215, 215, 310, 455, 400, 355, 285, 435,  50, 190,
       155,  15, 275, 440, 460, 260, 245, 470, 220,  10, 370,  15, 455,
        70, 320, 240, 425, 205, 300, 380, 115, 465, 420, 205, 515, 220,
        75, 420, 100, 255, 145,  40, 455, 305, 100,  55, 100, 475, 145,
       400, 465, 320, 140,   5, 360,  50, 460,  15, 310,  95, 500, 490,
       490, 120, 370,  55, 510, 480,  95, 110, 415, 345, 300, 260, 275,
       250,  60, 335, 510, 125, 220, 110, 395, 185, 165, 285,  50, 490,
       520,  75, 370,   5, 450, 425, 460, 265, 220, 280, 210, 300, 285,
       225, 515, 280, 415,  70, 245, 235])